apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: bridge-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: goapi
  type: LoadBalancer
